### ISSUE TITLE
Major bug in .profile - took me days to figure out

### ISSUE THREAD

**Issue by sla-te** [agkozak/dotfiles#1]
Alright so this had lead to getting into xterm fail safe upon logging in.

In your .profile

With this enabled, xterm will drop an error before logging in "unsupported number of arguments", on clicking OK, it will still load the session.
```bash
export PATH
set --  '/mingw64/bin' \
        "${HOME}/.gem/ruby/2.4.0/bin" \
        "${HOME}/.local/bin" \
        "${HOME}/go/bin" \
        "${HOME}/.cabal/bin" \
        "${HOME}/.config/composer/vendor/bin" \
        "${HOME}/.composer/vendor/bin" \
        "${HOME}/.luarocks/bin" \
        "${HOME}/ruby/gems/bin" \
       "${HOME}/.rvim/bin" \
        "${HOME}/bin"
```

Just below this part, there is this:
```bash
while [ $# -gt 0 ]; do
  [ -d "$1" ] && PATH="$1:${PATH}"
  shift
done
```

With both of these enabled, upon login one will land in an xterm failsafe session.

**Comment by agkozak** [comment]
I'm so sorry you had that experience, and thank you for identifying the offending code. I've just rewritten it as a proper function; I *think* that should fix your problem. Give the repo a pull and let me know. Also, I'd be curious which distribution you're using; I don't normally run into that problem myself.

**Comment by sla-te** [comment]
Thank you for the very quick reply. I am running debian buster. Ill pull and check if it works a bit later.

**Comment by agkozak** [comment]
Did the changes I made work out for you?

**Comment by sla-te** [comment]
sorry, that it took like forever for me to answer, it was working perfectly fine after you fixed it!
